### ISSUE TITLE
Remove dependencies

### ISSUE THREAD

**Issue by nickbalestra** [opentable/falcor-postman#1]
We should compose the static middleware before exposing it (See:  https://github.com/nickbalestra/express-serve-app/blob/master/middleware/middleware.js#L25-L28).

**Comment by mattiaerre** [comment]
this is really interesting @nickbalestra but what does it mean exactly?

**Comment by nickbalestra** [comment]
The final goal of the middleware, if decoupled as we are doing in this repo, is that someone can simply do app.use(configuredMiddleware) without having to setup other middlewares in order for it to work. One thing we are relying on is serving statics trough the static middleware, and we can just compose that dependency inside the falcor-postman middleware itself.  (see my [example](https://github.com/nickbalestra/express-serve-app/blob/master/middleware/middleware.js#L33-L35) where i did just that, sorry lines reference changed :)

**Comment by mattiaerre** [comment]
oh you are definitely right of course! but what about even something simpler such as:

https://github.com/RafalWilinski/express-status-monitor/blob/master/index.js#L88

using `fs.readFileSync` ?

what do you think?

**Comment by nickbalestra** [comment]
Mmm, not a big fan of the Sync methods in general. Any specific reason why going this way vs a simple middleware-composition might be better?

**Comment by mattiaerre** [comment]
nope no particular reason; let's explore more yours 👍

**Comment by mattiaerre** [comment]
close because of #7
