### ISSUE TITLE
what's next

### ISSUE THREAD

**Issue by mattiaerre** [opentable/falcor-postman#10]
- we need to inject '/model.json'; is it possible to save it into a data-\* attribute and read it from React? [must]
- ~~can we get rid of 'stage-1' in the end or we need to include it in the package.json? [must]~~ #11 
- we need to fix the tests :P [must] 
- ~~running `npm-check` I see a lot of unused packages (let's run it together) [should]~~
- ~~add pre-commit hook and decouple eslinting from tests [could]~~ #12 
- max number of queries to retain? [could]
- since 'middleware/' contains only I file shall we move it outside it? [curiosity]
- meta author; what's that? [curiosity]
- ...

**Comment by nickbalestra** [comment]
1 Agree 
3 Agree
5 How many queries does postman keep in his history? Does it have a limit? I think it adds a search to filter them down (that could be a nice feat to add later on, what ya think?)
6 I'm fine either way.
7 Defines the [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-name) of the author

**Comment by mattiaerre** [comment]
closing this issue for the time being

// cc @nickbalestra @chriscartlidge
