### ISSUE TITLE
Clean UI 

### ISSUE THREAD

**Issue by nickbalestra** [opentable/falcor-postman#13]
Rework the final UI for the app.

![screen shot 2016-10-04 at 14 37 41](https://cloud.githubusercontent.com/assets/389705/19076307/2b2ef2c4-8a40-11e6-985c-ddb37f5dfe7b.png)

**Comment by mattiaerre** [comment]
let's do it together during next 20% time 😉

**Comment by mattiaerre** [comment]
closing this issue because of #20
