### ISSUE TITLE
Dir Structure

### ISSUE THREAD

**Issue by nickbalestra** [opentable/falcor-postman#2]
Statics assets should be self-contained so that it will be pretty easy to set-up path for it and easier to install as a standalone middleware, I suggest the following structure:

-- app
-- middleware
---- bin // where we'll put the the self executable bundle
-- falcor-postman.js // main in package.json

**Comment by mattiaerre** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PximHN5r&#x2F;75-falcor-postman"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> falcor-postman</a>

**Comment by mattiaerre** [comment]
shall we close this issue? is this still relevant? // cc @nickbalestra

**Comment by nickbalestra** [comment]
addressed in #8
